Mark as abandoned
sonata-project/SonataDatagridBundle pull request #396
Opened 2021-12-05 17:05 UTC by VincentLanglet

2021-12-05 17:31 UTC, core23 requested changes
Too soon. We still use this for the page bundle

2021-12-05 17:36 UTC, VincentLanglet commented
> Too soon. We still use this for the page bundle

The DatagridBundle dependency was removed from PageBundle v4.
https://github.com/sonata-project/SonataPageBundle/blob/4.x/composer.json

2021-12-05 18:22 UTC, jordisala1991 approved these changes

2021-12-06 16:50 UTC, core23 approved these changes

2021-12-06 16:52 UTC, merged